list = [
    "772. Basic Calculator III",
    "2. Add Two Numbers",
    "3. Longest Substring Without Repeating Characters",
    "9. Palindrome Number",
    "12. Integer to Roman",
    "13. Roman to Integer",
    "253. Meeting Rooms II",
    "295. Find Median from Data Stream",
    "348. Design Tic-Tac-Toe",
    "362. Design Hit Counter",
    "15. 3Sum",
    "21. Merge Two Sorted Lists",
    "23. Merge k Sorted Lists",
    "843. Guess the Word",
    "994. Rotting Oranges",
    "31. Next Permutation",
    "32. Longest Valid Parentheses",
    "48. Rotate Image",
    "253. Meeting Rooms II",
    "295. Find Median from Data Stream",
    "348. Design Tic-Tac-Toe",
    "54. Spiral Matrix",
    "64. Minimum Path Sum",
    "103. Binary Tree Zigzag Level Order Traversal",
    "204. Count Primes",
    "211. Design Add and Search Words Data Structure",
    "215. Kth Largest Element in an Array",
    "224. Basic Calculator",
    "236. Lowest Common Ancestor of a Binary Tree",
    "239. Sliding Window Maximum",
    "253. Meeting Rooms II",
    "295. Find Median from Data Stream",
    "348. Design Tic-Tac-Toe",
    "362. Design Hit Counter",
    "380. Insert Delete GetRandom O(1)",
    "443. String Compression",
    "465. Optimal Account Balancing",
    "468. Validate IP Address",
    "545. Boundary of Binary Tree",
    "701. Insert into a Binary Search Tree",
    "1102. Path With Maximum Minimum Value",
    "1244. Design A Leaderboard",
    "1258. Synonymous Sentences",
    "1545. Find Kth Bit in Nth Binary String",
    "236. Lowest Common Ancestor of a Binary Tree",
    "239. Sliding Window Maximum",
    "253. Meeting Rooms II",
    "1570. Dot Product of Two Sparse Vectors",
    "1730. Shortest Path to Get Food",
]
print(len(list))
print(len(set(list)))
